#!/usr/bin/env ruby
# frozen_string_literal: true

require 'lib/log_parser'

case ARGV.first
when '-h', '--help'
  puts <<~TEXT
    usage: parse file_name.log
           parse [-h | --help]: display help
  TEXT
else
  Log_Parser.new(ARGB.first)
end
